const FETCH_ORGANIZATION = 'ORGANIZATION_FETCHED'
const FETCH_ORGANIZATION_PENDING = 'ORGANIZATION_FETCHED_PENDING'
const FETCH_ORGANIZATION_FULFILLED = 'ORGANIZATION_FETCHED_FULFILLED'
const FETCH_ORGANIZATION_REJECTED = 'ORGANIZATION_FETCHED_REJECTED'
const FETCH_EVENTS = 'EVENTS_FETCHED'
const FETCH_EVENTS_PENDING = 'EVENTS_FETCHED_PENDING'
const FETCH_EVENTS_FULFILLED = 'EVENTS_FETCHED_FULFILLED'
const FETCH_EVENTS_REJECTED = 'EVENTS_FETCHED_REJECTED'
const FETCH_EVENT_DETAILS = 'EVENT_DETAILS_FETCHED'
const FETCH_EVENT_DETAILS_PENDING = 'EVENT_FETCHED_PENDING'
const FETCH_EVENT_DETAILS_FULFILLED = 'EVENT_DETAILS_FETCHED_FULFILLED'
const FETCH_EVENT_DETAILS_REJECTED = 'EVENT_DETAILS_FETCHED_REJECTED'

export {
  FETCH_ORGANIZATION,
  FETCH_ORGANIZATION_PENDING,
  FETCH_ORGANIZATION_FULFILLED,
  FETCH_ORGANIZATION_REJECTED,
  FETCH_EVENTS,
  FETCH_EVENTS_PENDING,
  FETCH_EVENTS_FULFILLED,
  FETCH_EVENTS_REJECTED,
  FETCH_EVENT_DETAILS,
  FETCH_EVENT_DETAILS_PENDING,
  FETCH_EVENT_DETAILS_FULFILLED,
  FETCH_EVENT_DETAILS_REJECTED,
}
