const FETCH_ORGANIZATION = 'FETCH_ORGANIZATION'
const FETCH_ORGANIZATION_PENDING = 'FETCH_ORGANIZATION_PENDING'
const FETCH_ORGANIZATION_FULFILLED = 'FETCH_ORGANIZATION_FULFILLED'
const FETCH_ORGANIZATION_REJECTED = 'FETCH_ORGANIZATION_REJECTED'
const FETCH_EVENTS = 'FETCH_EVENTS'
const FETCH_EVENTS_PENDING = 'FETCH_EVENTS_PENDING'
const FETCH_EVENTS_FULFILLED = 'FETCH_EVENTS_FULFILLED'
const FETCH_EVENTS_REJECTED = 'FETCH_EVENTS_REJECTED'
const FETCH_EVENT_DETAILS = 'FETCH_EVENT_DETAILS'
const FETCH_EVENT_DETAILS_PENDING = 'FETCH_EVENT_DETAILS_PENDING'
const FETCH_EVENT_DETAILS_FULFILLED = 'FETCH_EVENT_DETAILS_FULFILLED'
const FETCH_EVENT_DETAILS_REJECTED = 'FETCH_EVENT_DETAILS_REJECTED'
const FETCH_SPEAKERS = 'FETCH_SPEAKERS'
const FETCH_SPEAKERS_PENDING = 'FETCH_SPEAKERS_PENDING'
const FETCH_SPEAKERS_FULFILLED = 'FETCH_SPEAKERS_FULFILLED'
const FETCH_SPEAKERS_REJECTED = 'FETCH_SPEAKERS_REJECTED'
const FETCH_PAST_EVENTS = 'FETCH_PAST_EVENTS'
const FETCH_PAST_EVENTS_PENDING = 'FETCH_PAST_EVENTS_PENDING'
const FETCH_PAST_EVENTS_FULFILLED = 'FETCH_PAST_EVENTS_FULFILLED'
const FETCH_PAST_EVENTS_REJECTED = 'FETCH_PAST_EVENTS_REJECTED'

export {
  FETCH_ORGANIZATION,
  FETCH_ORGANIZATION_PENDING,
  FETCH_ORGANIZATION_FULFILLED,
  FETCH_ORGANIZATION_REJECTED,
  FETCH_EVENTS,
  FETCH_EVENTS_PENDING,
  FETCH_EVENTS_FULFILLED,
  FETCH_EVENTS_REJECTED,
  FETCH_EVENT_DETAILS,
  FETCH_EVENT_DETAILS_PENDING,
  FETCH_EVENT_DETAILS_FULFILLED,
  FETCH_EVENT_DETAILS_REJECTED,
  FETCH_SPEAKERS,
  FETCH_SPEAKERS_PENDING,
  FETCH_SPEAKERS_FULFILLED,
  FETCH_SPEAKERS_REJECTED,
  FETCH_PAST_EVENTS,
  FETCH_PAST_EVENTS_PENDING,
  FETCH_PAST_EVENTS_FULFILLED,
  FETCH_PAST_EVENTS_REJECTED,
}
